{
 "title": "Benchmark",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Rates [m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "rate(pi_started_total[1m])", "legendFormat": "PI Started" },
    {
     "expr": "rate(pi_backpressure_total[1m])",
     "legendFormat": "PI Backpressure"
    },
    { "expr": "rate(jobs_completed_total[1m])", "legendFormat": "Jobs Completed" }
   ]
  },
  {
   "title": "Started PI in total in range",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(pi_started_total)", "legendFormat": "PI" },
    { "expr": "sum(pi_exception_total)", "legendFormat": "Errors" }
   ]
  },
  {
   "title": "Max cycle time in ms",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 7, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pi_cycletime_seconds_max * 1000"
    }
   ]
  },
  {
   "title": "Cycle time percentiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 12, "y": 8 },
   "targets": [
    { "expr": "pi_cycletime_seconds", "legendFormat": "{{quantile}}" }
   ]
  },
  {
   "title": "Cycle time in ms [1m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 8 },
   "targets": [
    {
     "expr": "rate(pi_cycletime_seconds_sum[1m]) / rate(pi_cycletime_seconds_count[1m]) * 1000",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "PI Exception Count Sum",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "pi_exception_total", "legendFormat": "{{exception}}" }
   ]
  },
  {
   "title": "Jobs Exception Count Sum",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "jobs_exception_total", "legendFormat": "{{exception}}" }
   ]
  }
 ]
}