{
 "title": "Event-classification-poc-report",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Events handled",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "pi_started_total", "legendFormat": "Events received" },
    {
     "expr": "job_completion_total{action=\"benchmark-task-1\"}",
     "legendFormat": "High priority Events"
    },
    {
     "expr": "job_completion_total{action=\"benchmark-task-2\"}",
     "legendFormat": "Low priority Events"
    },
    {
     "expr": "job_completion_total{action=\"benchmark-task-3\"}",
     "legendFormat": "Further Verification"
    },
    { "expression": "$D - ($A+$B+$C)", "type": "math" },
    {
     "expr": "rate(pi_started_total[1m]) - (rate(job_completion_total{action=\"benchmark-task-1\"}[1m]) + rate(job_completion_total{action=\"benchmark-task-2\"}[1m]) + rate(job_completion_total{action=\"benchmark-task-3\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Event type distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "job_completion_total{action=\"benchmark-task-1\"}",
     "legendFormat": "High Priority events"
    },
    {
     "expr": "job_completion_total{action=\"benchmark-task-2\"}",
     "legendFormat": "Low Priority events"
    },
    {
     "expr": "job_completion_total{action=\"benchmark-task-3\"}",
     "legendFormat": "Further verification "
    },
    {
     "expr": "PI_action_total{action=\"start\"}",
     "legendFormat": "All events"
    }
   ]
  },
  {
   "title": "Max time (in Secs) for each Task type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "job_timer_benchmark_task_1_seconds_max",
     "legendFormat": "High priority event - max time taken"
    },
    {
     "expr": "job_timer_benchmark_task_2_seconds_max",
     "legendFormat": "Low priority event - max time taken"
    },
    {
     "expr": "job_timer_benchmark_task_3_seconds_max",
     "legendFormat": "Further verification- max time taken"
    }
   ]
  },
  {
   "title": "Rate of Events handled / second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "rate(pi_started_total[1m])", "legendFormat": "Total Events Received /sec" },
    {
     "expr": "rate(job_completion_total{action=\"benchmark-task-1\"}[1m])",
     "legendFormat": "High priority Events / sec"
    },
    {
     "expr": "rate(job_completion_total{action=\"benchmark-task-2\"}[1m])",
     "legendFormat": "Low priority Events / sec"
    },
    {
     "expr": "rate(job_completion_total{action=\"benchmark-task-3\"}[1m])",
     "legendFormat": "Further Verification / sec"
    }
   ]
  },
  {
   "title": "AI Classification - Average time (s)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "job_timer_benchmark_task_1_seconds_sum / job_timer_benchmark_task_1_seconds_count"
    }
   ]
  },
  {
   "title": "Rates [m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 16 },
   "targets": [
    { "expr": "rate(pi_started_total[1m])", "legendFormat": "PI Started" },
    {
     "expr": "rate(pi_backpressure_total[1m])",
     "legendFormat": "PI Backpressure"
    },
    { "expr": "rate(jobs_completed_total[1m])", "legendFormat": "Jobs Completed" },
    { "expr": "rate(pi_completed_total[1m])", "legendFormat": "PI Completed" },
    {
     "expr": "rate(jobs_completed_total[1m]) / rate(pi_started_total[1m])",
     "legendFormat": "Task/PI Ratio"
    }
   ]
  },
  {
   "title": "Jobs / PI Ratio",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(jobs_completed_total[1m]) / rate(pi_started_total[1m])"
    }
   ]
  },
  {
   "title": "PI Exception Count Sum",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 24 },
   "targets": [
    { "expr": "pi_exception_total", "legendFormat": "{{exception}}" }
   ]
  },
  {
   "title": "Jobs Exception Count Sum",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 24 },
   "targets": [
    { "expr": "jobs_exception", "legendFormat": "{{exception}}" }
   ]
  },
  {
   "title": "Started PI in total in range",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(pi_started_total)", "legendFormat": "PI" },
    { "expr": "sum(pi_exception_total)", "legendFormat": "Errors" }
   ]
  },
  {
   "title": "Cycle time percentiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 7, "y": 32 },
   "targets": [
    { "expr": "pi_cycletime_seconds", "legendFormat": "{{quantile}}" }
   ]
  },
  {
   "title": "Spring Executor Completed Tasks [1m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 32 },
   "targets": [
    {
     "expr": "rate(executor_completed_tasks_total[1m])",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}